import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "./(landing)/Navbar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-lite"></script>
      <body className={inter.className}>
        <div className="">
          {/* <Navbar/> */}
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
